" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Neovim defaults for Vim
set autoindent
set autoread
set backspace=indent,eol,start
set complete-=i
set display=lastline
set encoding=utf-8
set formatoptions=tcqj
set history=10000
set hlsearch
set incsearch
if exists('+langnoremap')
    set langnoremap
endif
set laststatus=2
set listchars=tab:>\ ,trail:-,nbsp:+
set mouse=a
set nrformats=hex
set sessionoptions-=options
set tabpagemax=50
set tags=./tags;,tags
set ttyfast
set viminfo+=!

" Mimic bash behavior for command autocompletion
set wildmenu
set wildmode=list:longest

" Hide command and mode on command line
set noshowcmd
set noshowmode

" Automatically set directory to current buffer's
set autochdir

" Switch syntax highlighting on
syntax enable

" Disable search highlighting
set nohlsearch

" Smart case searching
set ignorecase
set smartcase

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Show relative line numbers
set number
set relativenumber

" Allow hidden buffers, don't limit to 1 file per window/split
set hidden

" Spaces instead of tabs
set tabstop=4
set shiftwidth=4
set expandtab

" Leader
let mapleader="\<Space>"

" Natural splitting
set splitbelow
set splitright
nnoremap <leader>j <C-W><C-J>
nnoremap <leader>k <C-W><C-K>
nnoremap <leader>l <C-W><C-L>
nnoremap <leader>h <C-W><C-H>

" Buffer management
nnoremap <leader>[ :bp<CR>
nnoremap <leader>] :bn<CR>

" Pathogen
function PathogenInfect(filetype)
    execute pathogen#infect('bundles/vim/' . a:filetype . '/{}')
    if v:progname == 'nvim' || (v:progname == 'vim' && v:version >= 800)
        execute pathogen#infect('bundles/nvim/' . a:filetype . '/{}')
    endif
endfunction
execute PathogenInfect('all')

colorscheme minimalist

" CtrlP
let g:ctrlp_map = '<leader>p'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ca'
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" NERDTree
nnoremap <leader>\ :NERDTreeToggle<CR>

" Commentary
map g/ gc

" Use deoplete for autocompletion
set omnifunc=syntaxcomplete#Complete
let g:deoplete#enable_at_startup = 1

" Use echodoc to move autocompletion preview window to command line
set completeopt-=preview
let g:echodoc_enable_at_startup = 1

" Tab through pop-up menus
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"

" Default Python paths to ensure pynvim exists when changing environments
let g:python_host_prog  = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

" ALE lint on open/save only
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0

" Lightline
set showtabline=2
let g:bufferline_echo = 0
let g:lightline = {
    \ 'colorscheme': 'PaperColor_light',
    \ 'tabline': {
    \   'left': [ [ 'bufferline' ] ],
    \ },
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
    \ },
    \ 'component_expand': {
    \   'bufferline': 'LightlineBufferline',
    \ },
    \ 'component_type': {
    \   'bufferline': 'tabsel',
    \ },
    \ }
function! LightlineBufferline()
    call bufferline#refresh_status()
    return [ g:bufferline_status_info.before, g:bufferline_status_info.current, g:bufferline_status_info.after ]
endfunction

" Promptline bash status bar
" Uncomment and run :PromptlineSnapshot! ../bash/.shell_prompt.sh
" execute pathogen#infect('bundles/utils/promptline.vim')
" let g:promptline_theme = 'lightline'
" let g:promptline_preset = {
" 	\ 'a'   : [ promptline#slices#user() ],
" 	\ 'b'   : [ promptline#slices#cwd({ 'dir_limit': 2 }) ],
" 	\ 'c'   : [ promptline#slices#vcs_branch() ],
" 	\ 'warn': [ promptline#slices#last_exit_code() ],
" 	\ }
" let g:promptline_powerline_symbols = 0

" tmuxline
" Uncomment and run :Tmuxline
" execute pathogen#infect('bundles/utils/tmuxline.vim')
" let g:tmuxline_theme = 'lightline'
" let g:tmuxline_powerline_separators = 0
