" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Make backspace behave in a sane manner.
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax enable

" Pathogen
execute pathogen#infect()

" Solarized Colors
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Show line numbers
set number

" Allow hidden buffers, don't limit to 1 file per window/split
set hidden

" Save last 100 commands
set history=100

" Spaces instead of tabs
:set expandtab

" Airline
set laststatus=2
let g:airline_theme="luna"

" Leader
let mapleader="\<Space>"

" Natural splitting
set splitbelow
set splitright
nnoremap <leader>j <C-W><C-J>
nnoremap <leader>k <C-W><C-K>
nnoremap <leader>l <C-W><C-L>
nnoremap <leader>h <C-W><C-H>
cabbrev split vsplit
cabbrev hsplit split

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" CtrlP
let g:ctrlp_map = "<leader>p"
let g:ctrlp_cmd = "CtrlP"
let g:ctrlp_working_path_mode = "ra"
let g:ctrlp_user_command = [".git", "cd %s && git ls-files -co --exclude-standard"]
