#!/usr/bin/env bash

# tmux status bar based on the onedark theme.

if [ "${COLORTERM}" = truecolor ] || [ "${COLORTERM}" = 24bit ]; then
    TMUX_COLOR_GRAY_0="#abb2bf"
    TMUX_COLOR_GRAY_1="#5c6370"
    TMUX_COLOR_GRAY_2="#31353f"
    TMUX_COLOR_PURPLE="#c678dd"
    TMUX_COLOR_GREEN="#98c379"
    TMUX_COLOR_YELLOW="#e5c07b"
    TMUX_COLOR_RED="#e86671"
else
    TMUX_COLOR_GRAY_0="colour255"
    TMUX_COLOR_GRAY_1="colour243"
    TMUX_COLOR_GRAY_2="colour238"
    TMUX_COLOR_PURPLE="colour176"
    TMUX_COLOR_GREEN="colour114"
    TMUX_COLOR_YELLOW="colour180"
    TMUX_COLOR_RED="colour168"
fi

TMUX_COLOR_FG_0="${TMUX_COLOR_GRAY_0}"
TMUX_COLOR_FG_1="${TMUX_COLOR_GRAY_1}"
TMUX_COLOR_BG="${TMUX_COLOR_GRAY_2}"
TMUX_COLOR_THEME="${TMUX_COLOR_PURPLE}"

tmux setenv -g "TMUX_COLOR_FG_0" "${TMUX_COLOR_FG_0}"
tmux setenv -g "TMUX_COLOR_FG_1" "${TMUX_COLOR_FG_1}"
tmux setenv -g "TMUX_COLOR_BG" "${TMUX_COLOR_BG}"
tmux setenv -g "TMUX_COLOR_THEME" "${TMUX_COLOR_THEME}"
tmux setenv -g "TMUX_COLOR_PURPLE" "${TMUX_COLOR_PURPLE}"
tmux setenv -g "TMUX_COLOR_GREEN" "${TMUX_COLOR_GREEN}"
tmux setenv -g "TMUX_COLOR_YELLOW" "${TMUX_COLOR_YELLOW}"
tmux setenv -g "TMUX_COLOR_RED" "${TMUX_COLOR_RED}"

tmux set -g status-justify "left"
tmux set -g status "on"
tmux set -g status-left-style "none"
tmux set -g status-interval "1"
tmux set -g message-command-style "fg=${TMUX_COLOR_FG_0}"
tmux set -g message-command-style "bg=${TMUX_COLOR_BG}"
tmux set -g status-right-style "none"
tmux set -g pane-active-border-style "fg=${TMUX_COLOR_THEME}"
tmux set -g status-style "none,bg=${TMUX_COLOR_BG}"
tmux set -g message-style "fg=${TMUX_COLOR_FG_0},bg=${TMUX_COLOR_BG}"
tmux set -g pane-border-style "fg=${TMUX_COLOR_FG_1}"
tmux set -g status-right-length "100"
tmux set -g status-left-length "100"
tmux setw -g window-status-activity-style "none"
tmux setw -g window-status-separator ""
tmux setw -g window-status-style "none,fg=${TMUX_COLOR_FG_0},bg=${TMUX_COLOR_BG}"
tmux set -g status-left "#[fg=${TMUX_COLOR_BG},bg=${TMUX_COLOR_THEME},bold] #S "
tmux set -g status-right "#[fg=${TMUX_COLOR_THEME}]#{?client_prefix,P,} #(~/.config/tmux/network.sh) #(~/.config/tmux/memory.sh) #(~/.config/tmux/cpu.sh) #[fg=${TMUX_COLOR_BG},bg=${TMUX_COLOR_THEME},bold] #h "
tmux setw -g window-status-format " #[fg=${TMUX_COLOR_FG_1}]#I:#W"
tmux setw -g window-status-current-format " #[fg=${TMUX_COLOR_FG_0}]#{?window_zoomed_flag,,#{?pane_synchronized,,#I}}:#W"
