#!/usr/bin/env bash

export INPUTRC="${HOME}/.config/inputrc"
export HOMEBREW_BUNDLE_FILE="${HOME}/.config/Brewfile"

# Set EDITOR variable to nvim/vim
if [ -f /usr/local/bin/nvim ]; then
    export EDITOR=/usr/local/bin/nvim
elif [ -f /usr/local/bin/vim ]; then
    export EDITOR=/usr/local/bin/vim
else
    export EDITOR=/usr/bin/vim
fi

export CLICOLOR=1
export LSCOLORS="GxFxCxDxBxegedabagaced" # Mac OS
export LS_COLORS="di=1;36:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=34;43" # Linux

export GREP_OPTIONS="--color"
